# Streamlit Secrets Configuration
# Add your API keys here for production use

# Example configuration (replace with your actual keys):
# GOOGLE_GEMINI_API_KEY = "your_google_gemini_key_here"
# OPENAI_API_KEY = "your_openai_key_here"
# STABILITY_API_KEY = "your_stability_ai_key_here"
# YOUTUBE_API_KEY = "your_youtube_api_key_here"

# For now, using placeholder values
GOOGLE_GEMINI_API_KEY = ""
OPENAI_API_KEY = ""
STABILITY_API_KEY = ""
YOUTUBE_API_KEY = ""
